"""Render a single-spectrum Fityk Lua script with one shared $hwhm."""

from __future__ import annotations

from pathlib import Path

from .models import BackgroundKind, FitMode, PeakSeed, Session


class LuaRenderError(ValueError):
    """Raised when a Lua script cannot be rendered."""


def lua_string(value: str) -> str:
    if "]=]" not in value:
        return f"[=[{value}]=]"
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def lua_run(command: str) -> str:
    return f"run({lua_string(command)})"


def fityk_path_arg(path: str | Path) -> str:
    text = str(path).replace("\\", "/")
    if "'" not in text:
        return f"'{text}'"
    if '"' not in text:
        return f'"{text}"'
    raise LuaRenderError(f"Path cannot contain both quote types: {text}")


def _background_define(kind: BackgroundKind, x_mid: float) -> list[str]:
    if kind is BackgroundKind.NONE:
        return []
    if kind is BackgroundKind.CONSTANT:
        return [lua_run("define Bg0(offset) = offset")]
    if kind is BackgroundKind.LINEAR:
        return [
            lua_run(
                f"define Bg1(intercept, slope) = intercept + slope * (x - {x_mid:.12g})"
            )
        ]
    if kind is BackgroundKind.QUADRATIC:
        return [
            lua_run(
                "define Bg2(intercept, slope, curvature) = "
                f"intercept + slope * (x - {x_mid:.12g}) "
                f"+ curvature * (x - {x_mid:.12g})^2"
            )
        ]
    raise LuaRenderError(f"Unknown background: {kind!r}")


def _background_add(kind: BackgroundKind) -> str | None:
    if kind is BackgroundKind.NONE:
        return None
    if kind is BackgroundKind.CONSTANT:
        return lua_run("@0: F += Bg0(~0)")
    if kind is BackgroundKind.LINEAR:
        return lua_run("@0: F += Bg1(~0, ~0)")
    if kind is BackgroundKind.QUADRATIC:
        return lua_run("@0: F += Bg2(~0, ~0, ~0)")
    raise LuaRenderError(f"Unknown background: {kind!r}")


def _hwhm_assignment(session: Session) -> str:
    hwhm = session.hwhm
    lo = max(hwhm * 0.25, 1e-8)
    hi = hwhm * 4.0
    if session.refine_shared_fwhm:
        return lua_run(f"$hwhm = ~{hwhm:.12g} [{lo:.12g}:{hi:.12g}]")
    return lua_run(f"$hwhm = {hwhm:.12g}")


def _shape_assignment(session: Session) -> str:
    shape = float(session.shape)
    if session.refine_shared_shape:
        return lua_run(f"$shape = ~{shape:.12g} [0:1]")
    return lua_run(f"$shape = {shape:.12g}")


def _peak_command(session: Session, seed: PeakSeed) -> str:
    height = max(float(seed.height), 0.0)
    center = float(seed.center)
    if session.mode is FitMode.DISTRIBUTION:
        center_arg = f"{center:.12g}"
    else:
        slack = max(session.center_slack_factor * session.fwhm, 1e-12)
        lo = center - slack
        hi = center + slack
        center_arg = f"~{center:.12g} [{lo:.12g}:{hi:.12g}]"
    return lua_run(
        f"@0: F += PseudoVoigt(~{height:.12g} [0:1e12], {center_arg}, $hwhm, $shape)"
    )


def render_fit_lua(
    session: Session,
    seeds: list[PeakSeed],
    *,
    input_xy: str | Path,
    output_prefix: str | Path,
    xmin: float,
    xmax: float,
) -> str:
    if not seeds:
        raise LuaRenderError("Cannot render Lua without peak seeds.")
    prefix = Path(output_prefix)
    peaks_path = fityk_path_arg(prefix.with_suffix(".peaks"))
    peaks_err_path = fityk_path_arg(prefix.with_name(prefix.name + ".peaks_err"))
    state_path = fityk_path_arg(prefix.with_suffix(".fit"))
    log_path = fityk_path_arg(prefix.with_suffix(".log"))
    x_mid = 0.5 * (xmin + xmax)
    lines = [
        "-- Generated by PeakComb. Edit session.yaml, not this file.",
        f"-- mode={session.mode.value} n_peaks={len(seeds)} fwhm={session.fwhm:.12g}",
        "",
        "local function run(command)",
        "    F:execute(command)",
        "end",
        "",
        lua_run("set autoplot = 0"),
        lua_run("set fit_replot = 0"),
        lua_run("set verbosity = -1"),
        lua_run("set box_constraints = 1"),
        lua_run(f"set fitting_method = {session.fitting_method}"),
        lua_run(f"set max_wssr_evaluations = {int(session.max_wssr_evaluations)}"),
        lua_run(f"set max_fitting_time = {float(session.max_fitting_time):g}"),
        "",
        lua_run(f"@+ < {fityk_path_arg(input_xy)}"),
        lua_run(f"@0: A = (x >= {xmin:.12g} and x <= {xmax:.12g})"),
        lua_run("@0: F = 0"),
        "",
        *_background_define(session.background, x_mid),
    ]
    add_bkg = _background_add(session.background)
    if add_bkg:
        lines.append(add_bkg)
    lines.extend(
        [
            "",
            _hwhm_assignment(session),
            _shape_assignment(session),
            "",
        ]
    )
    for seed in seeds:
        lines.append(_peak_command(session, seed))
    lines.extend(
        [
            "",
            lua_run("@0: fit"),
            "",
            "local wssr = F:get_wssr(0)",
            f"local log_path = {lua_string(str(Path(output_prefix).with_suffix('.log')).replace(chr(92), '/'))}",
            "local log_file = io.open(log_path, 'w')",
            "if log_file then",
            "    log_file:write(string.format('FIT_OK\\twssr=%.12g\\tn_peaks=%d\\n', wssr, "
            + str(len(seeds))
            + "))",
            "    log_file:close()",
            "end",
            lua_run(f"@0: info peaks > {peaks_path}"),
            lua_run(f"@0: info peaks_err > {peaks_err_path}"),
            lua_run(f"info state > {state_path}"),
        ]
    )
    # Keep log_path used even if Lua optimizer drops locals — the file write is the contract.
    _ = log_path
    return "\n".join(lines) + "\n"
